In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense, Activation, Dropout
from tensorflow.keras.models import Sequential

/Users/tungdt/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [2]:
# Tạo input layer có kích thước 3
input_layer = keras.Input(shape=(3,))
weights = np.array([[0.2, 0.8, -0.5],
                    [0.5, -0.91, 0.26],
                    [-0.26, -0.27, 0.17]])
bias = np.array([2, 3, 0.5])
print(input_layer.shape)
print(weights.shape)
print(bias.shape)

(None, 3)
(3, 3)
(3,)


In [6]:
hidden_layer = Dense(3, activation='sigmoid')
output_layer = hidden_layer(input_layer)

model = keras.Model(inputs=input_layer, outputs=output_layer)
hidden_layer.set_weights([weights, bias])

model.summary()


Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 3)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 12 (48.00 B)

 Trainable params: 12 (48.00 B)

 Non-trainable params: 0 (0.00 B)

In [8]:
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])
y = model.predict(X)
print("Output:\n", y)
weights, biases = hidden_layer.get_weights()
print("Weights:\n", weights)
print("Biases:\n", biases)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
Output:
 [[0.9926287  0.99127054 0.9786806 ]
 [0.99962103 0.9956922  0.99971545]
 [0.9999806  0.99787897 0.9999963 ]
 [0.999999   0.99895686 1.        ]]
Weights:
 [[-0.29604173 -0.9232099   0.09479833]
 [ 0.66427135  0.82486534  0.82158303]
 [ 0.6234212   0.33525348  0.52954173]]
Biases:
 [2.  3.  0.5]
