In [3]:
import numpy as np
# create an array from a list
a = [1, 3, 5, 7, 9]
print(a, type(a))
b = np.array(a)
print(b, type(b))

[1, 3, 5, 7, 9] <class 'list'>
[1 3 5 7 9] <class 'numpy.ndarray'>


In [4]:
# array indexing: similar as list
print(b[0]) # 1st item
print(b[-1]) # last item

1
9


In [5]:
# slicing same as list
print(b[1::])

[3 5 7 9]


In [7]:
a = np.zeros(4) # create an array of 4 zeros
print(a)
a = np.ones(4)
print(a)

[0. 0. 0. 0.]
[1. 1. 1. 1.]


In [9]:
a = np.arange(1, 10)
print(a)
a = np.arange(1, 20, 2)
print(a)

[1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19]


In [94]:
a = np.random.rand(3, 3)
print(a)

[[0.72484942 0.58385961 0.75055194]
 [0.39687739 0.16872112 0.65129095]
 [0.8386662  0.87122288 0.735226  ]]


In [95]:
b = a * 10
print(b)

[[7.24849422 5.83859613 7.50551942]
 [3.96877388 1.68721119 6.51290953]
 [8.38666204 8.71222876 7.35226003]]


In [13]:
a = [1, 2, 3]
b = [4, 5, 6]
c = a + b
print(c)
d = ['hello', 'python']
e = c + d
print(e)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 'hello', 'python']


In [14]:
arr_a = np.array(a)
arr_b = np.array(b)
arr_c = arr_a + arr_b
print(arr_c)

[5 7 9]


In [15]:
f = a * 2
arr_f = arr_a * 2
print(f)
print(arr_f)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [ ]:
arr_b = arr_b - 1
print(arr_b)


[3 4 5]


In [17]:
arr_b -= 1
print(arr_b)

[2 3 4]


In [19]:
print(arr_a, arr_b, sep='\n')
arr_c = arr_a * arr_b
print(arr_c)

[1 2 3]
[2 3 4]
[ 2  6 12]


In [21]:
a = [1, 2.0, 3, 4.5]
arr_a = np.array(a)
print(a)
print(arr_a)

[1, 2.0, 3, 4.5]
[1.  2.  3.  4.5]


In [22]:
a = [1, 2.0, 3, 4.5, 'hello']
arr_a = np.array(a)
print(a)
print(arr_a)

[1, 2.0, 3, 4.5, 'hello']
['1' '2.0' '3' '4.5' 'hello']


In [28]:
numbers = np.random.randint(0, 10, 6) # generate 6 random integers
print(numbers)

[2 5 8 4 9 4]


In [29]:
count = 0
for n in numbers:
    if n > 5:
        count += 1
print(count)

2


In [30]:
numbers_twice = numbers * 2
print(numbers_twice)

[ 4 10 16  8 18  8]


In [34]:
import random as rd
a = rd.sample(range(100), 10) # generate a list of 10 random number
b = np.random.randint(0, 100, 10)
print(a, b, sep='\n')

[99, 71, 87, 88, 56, 11, 61, 24, 64, 78]
[78 52 53 54 73  4 96 75  4 75]


In [32]:
# get even numbers from list
evens_a = [n for n in a if n % 2 == 0]
print(evens_a, type(evens_a))

[70, 22, 14, 6, 62] <class 'list'>


In [38]:
evens_b = [int(n) for n in b if n % 2 == 0]
print(evens_b, type(evens_b))

[78, 52, 54, 4, 96, 4] <class 'list'>


In [ ]:
evens_b = b[b % 2 == 0] # boolean indexing
print(evens_b, type(evens_b))

[78 52 54  4 96  4] <class 'numpy.ndarray'>


In [40]:
print(b % 2 == 0)

[ True  True False  True False  True  True False  True False]


In [43]:
b = np.random.randint(0, 100, 10)
print(b)
# get array of odd numbers
odd_b = b[b % 2 == 1]
print(odd_b)
# get array of numbers > 50
big_b = b[b > 50]
print(big_b)

[52 81 83 28 64 77 32 13 24 57]
[81 83 77 13 57]
[52 81 83 64 77 57]


In [52]:
names = np.array(['Alice Keller', 'Bob Smith', 'Charlie Brown', 'Diana Mike Prince', 'Eve Onana Adams'])
# get long name (length > 15 characters)
long_names = names[np.char.str_len(names) > 12]
print(long_names)
# get names that have middle names
middle_names = names[np.char.count(names, ' ') > 1]
print(middle_names)

['Charlie Brown' 'Diana Mike Prince' 'Eve Onana Adams']
['Diana Mike Prince' 'Eve Onana Adams']


In [60]:
numbers = np.random.randint(-100, 100, 10)
print(numbers)

[-93 -40 -51 -23  80   1  19 -14 -20 -38]


In [59]:
for i in range(len(numbers)):
    if numbers[i] < 0:
        numbers[i] = 0
print(numbers)

[ 0 79  5 18 11  0 13 52 41 20]


In [61]:
numbers[numbers < 0] = 0
print(numbers)

[ 0  0  0  0 80  1 19  0  0  0]


In [62]:
numbers = np.random.randint(-100, 100, 10)
print(numbers)
numbers[numbers < 0] *= -1
print(numbers)

[-77   4  71 -76 -80 -14  -8  11  71 -96]
[77  4 71 76 80 14  8 11 71 96]


In [63]:
names = np.array(['John', 'Mike', '', 'Alice', 'Bob', '', 'Charlie'])
# convert empty string to a default value ('Paul')
names[names == ''] = 'Paul'
print(names)

['John' 'Mike' 'Paul' 'Alice' 'Bob' 'Paul' 'Charlie']


In [71]:
a = np.ones(4, dtype=int)
b = np.zeros(4, dtype=int)
c = a + b
print(c)
c = np.concatenate([a, b])
print(c)

[1 1 1 1]
[1 1 1 1 0 0 0 0]


In [74]:
print(type(c), np.shape(c))

<class 'numpy.ndarray'> (8,)


In [79]:
d = np.reshape(c, (2, 4))
print(d, np.shape(d))
e = np.reshape(c, (4, 2))
print(e, np.shape(e))

[[1 1 1 1]
 [0 0 0 0]] (2, 4)
[[1 1]
 [1 1]
 [0 0]
 [0 0]] (4, 2)


In [81]:
print(c)
d = np.reshape(c, (8, 1))
e = np.reshape(c, (1, 8))
print(d)
print(e)

[1 1 1 1 0 0 0 0]
[[1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]]
[[1 1 1 1 0 0 0 0]]


In [84]:
print(c[0])
print(d[0])
print(d[0][0])
print(e[0])
print(e[0][0])

1
[1]
1
[1 1 1 1 0 0 0 0]
1


In [90]:
a = np.random.randint(1, 10, 9)
a = np.reshape(a, (3, 3))
print(a)

[[5 9 3]
 [2 4 4]
 [4 1 6]]


In [91]:
b = np.random.randint(1, 10, 9)
b = np.reshape(b, (3, 3))
print(b)

[[8 7 1]
 [4 1 3]
 [8 4 1]]


In [92]:
print(a + b)
print(a - b)
print(a * b)

[[13 16  4]
 [ 6  5  7]
 [12  5  7]]
[[-3  2  2]
 [-2  3  1]
 [-4 -3  5]]
[[40 63  3]
 [ 8  4 12]
 [32  4  6]]


In [93]:
c = np.dot(a, b)
print(c)

[[100  56  35]
 [ 64  34  18]
 [ 84  53  13]]
